services:
  db:
    container_name: db-deliver
    image: postgres:latest
    environment:
      POSTGRES_USER: deliver
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deliver_it
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "15432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: